import pandas as pd

states_color = {'Alabama': 94.65,
 'Alaska': 1.264,
 'Arizona': 57.05,
 'Arkansas': 56.43,
 'California': 241.7,
 'Colorado': 49.33,
 'Connecticut': 739.1,
 'Delaware': 464.3,
 'District of Columbia': 10065,
 'Florida': 353.4,
 'Georgia': 169.5,
 'Hawaii': 214.1,
 'Idaho': 19.15,
 'Illinois': 231.5,
 'Indiana': 181.7,
 'Iowa': 54.81,
 'Kansas': 35.09,
 'Kentucky': 110,
 'Louisiana': 105,
 'Maine': 43.04,
 'Maryland': 596.3,
 'Massachusetts': 840.2,
 'Michigan': 173.9,
 'Minnesota': 67.14,
 'Mississippi': 63.5,
 'Missouri': 87.26,
 'Montana': 6.858,
 'Nebraska': 23.97,
 'Nevada': 24.8,
 'New Hampshire': 147,
 'New Jersey': 1189,
 'New Mexico': 17.16,
 'New York': 412.3,
 'North Carolina': 198.2,
 'North Dakota': 9.916,
 'Ohio': 281.9,
 'Oklahoma': 55.22,
 'Oregon': 40.33,
 'Pennsylvania': 284.3,
 'Rhode Island': 1006,
 'South Carolina': 155.4,
 'South Dakota': 98.07,
 'Tennessee': 88.08,
 'Texas': 98.07,
 'Utah': 34.3,
 'Vermont': 67.73,
 'Virginia': 204.5,
 'Washington': 102.6,
 'West Virginia': 77.06,
 'Wisconsin': 105.2,
 'Wyoming': 5.851}


states_abbr = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

states_name_abbr = { 'Alabama': 'AL',
                     'Alaska': 'AK',
                     'American Samoa': 'AS',
                     'Arizona': 'AZ',
                     'Arkansas': 'AR',
                     'California': 'CA',
                     'Colorado': 'CO',
                     'Connecticut': 'CT',
                     'Delaware': 'DE',
                     'District of Columbia': 'DC',
                     'Florida': 'FL',
                     'Georgia': 'GA',
                     'Guam': 'GU',
                     'Hawaii': 'HI',
                     'Idaho': 'ID',
                     'Illinois': 'IL',
                     'Indiana': 'IN',
                     'Iowa': 'IA',
                     'Kansas': 'KS',
                     'Kentucky': 'KY',
                     'Louisiana': 'LA',
                     'Maine': 'ME',
                     'Maryland': 'MD',
                     'Massachusetts': 'MA',
                     'Michigan': 'MI',
                     'Minnesota': 'MN',
                     'Mississippi': 'MS',
                     'Missouri': 'MO',
                     'Montana': 'MT',
                     'National': 'NA',
                     'Nebraska': 'NE',
                     'Nevada': 'NV',
                     'New Hampshire': 'NH',
                     'New Jersey': 'NJ',
                     'New Mexico': 'NM',
                     'New York': 'NY',
                     'North Carolina': 'NC',
                     'North Dakota': 'ND',
                     'Northern Mariana Islands': 'MP',
                     'Ohio': 'OH',
                     'Oklahoma': 'OK',
                     'Oregon': 'OR',
                     'Pennsylvania': 'PA',
                     'Puerto Rico': 'PR',
                     'Rhode Island': 'RI',
                     'South Carolina': 'SC',
                     'South Dakota': 'SD',
                     'Tennessee': 'TN',
                     'Texas': 'TX',
                     'Utah': 'UT',
                     'Vermont': 'VT',
                     'Virgin Islands': 'VI',
                     'Virginia': 'VA',
                     'Washington': 'WA',
                     'West Virginia': 'WV',
                     'Wisconsin': 'WI',
                     'Wyoming': 'WY'}

states_abbr_name = {
                    'AK': 'Alaska',
                    'AL': 'Alabama',
                    'AR': 'Arkansas',
                    'AS': 'American Samoa',
                    'AZ': 'Arizona',
                    'CA': 'California',
                    'CO': 'Colorado',
                    'CT': 'Connecticut',
                    'DC': 'District of Columbia',
                    'DE': 'Delaware',
                    'FL': 'Florida',
                    'GA': 'Georgia',
                    'GU': 'Guam',
                    'HI': 'Hawaii',
                    'IA': 'Iowa',
                    'ID': 'Idaho',
                    'IL': 'Illinois',
                    'IN': 'Indiana',
                    'KS': 'Kansas',
                    'KY': 'Kentucky',
                    'LA': 'Louisiana',
                    'MA': 'Massachusetts',
                    'MD': 'Maryland',
                    'ME': 'Maine',
                    'MI': 'Michigan',
                    'MN': 'Minnesota',
                    'MO': 'Missouri',
                    'MP': 'Northern Mariana Islands',
                    'MS': 'Mississippi',
                    'MT': 'Montana',
                    'NA': 'National',
                    'NC': 'North Carolina',
                    'ND': 'North Dakota',
                    'NE': 'Nebraska',
                    'NH': 'New Hampshire',
                    'NJ': 'New Jersey',
                    'NM': 'New Mexico',
                    'NV': 'Nevada',
                    'NY': 'New York',
                    'OH': 'Ohio',
                    'OK': 'Oklahoma',
                    'OR': 'Oregon',
                    'PA': 'Pennsylvania',
                    'PR': 'Puerto Rico',
                    'RI': 'Rhode Island',
                    'SC': 'South Carolina',
                    'SD': 'South Dakota',
                    'TN': 'Tennessee',
                    'TX': 'Texas',
                    'UT': 'Utah',
                    'VA': 'Virginia',
                    'VI': 'Virgin Islands',
                    'VT': 'Vermont',
                    'WA': 'Washington',
                    'WI': 'Wisconsin',
                    'WV': 'West Virginia',
                    'WY': 'Wyoming'}

def state_values(svalue, us_states, outfile):
    """
    svalues: a dict  {State:value}
    template: template us-states json file.
    """
    with open(us_states) as jfile:
        with open(outfile, 'w') as jout:
            for l in jfile:
                if "FeatureCollection" not in l and "]};" not in l:
                    jdata = json.loads(l.rstrip(',\n'))
                    jdata['properties']['density'] = svalue[jdata['properties']['name']]
                    jout.write(json.dumps(jdata)+",\n")
                elif "FeatureCollection" in l or "]};" in l:
                    jout.write(l)
